### ISSUE TITLE
Fix all vlib parsing issues

### ISSUE THREAD

**Issue by hungrybluedev** [nedpals/tree-sitter-v#10]
Currently, these are the files in `vlib` that our parser is unable to parse. They all have at least one parsing error. The goal is to get this list close to to 0 before the public release of VLS.

- [x] builtin/builtin_d_gcboehm.v
- [ ] builtin/builtin_nix.c.v - refer to #14
- [ ] builtin/builtin_windows.c.v - refer to #14
- [x] builtin/cfns.c.v
- [x] builtin/int.v
- [ ] builtin/linux_bare/memory_managment.v - refer to #14 
- [ ] builtin/map.v - similar to #14 
- [ ] builtin/sorted_map.v - uses a lowercases name for struct: `mapnode`
- [x] cli/help.v - will get fixed with new string interpolation syntax on line 70
- [x] clipboard/x11/clipboard.c.v
- [x] context/cancel.v
- [x] context/deadline.v
- [x] context/empty.v
- [x] fontstash/fontstash.v
- [x] log/log.v
- [x] mysql/\_cdefs_nix.c.v
- [x] mysql/\_cdefs_windows.c.v
- [x] mysql/\_cdefs.c.v
- [x] mysql/orm.v
- [x] mysql/result.v
- [x] mysql/stmt.c.v
- [x] net/address_darwin.c.v
- [x] net/address_freebsd.c.v
- [x] net/html/parser.v
- [x] net/http/status.v
- [x] net/openssl/c.v
- [x] net/smtp/smtp.v
- [x] net/socket_options.c.v
- [x] net/tcp_read_line.v
- [x] net/unix/stream_nix.v
- [x] net/urllib/urllib.v
- [x] os/file.c.v
- [x] os/os_c.v
- [x] os/os_nix.c.v
- [x] os/signal.c.v
- [x] regex/regex_opt.v
- [x] sokol/audio/audio.v
- [x] sokol/gfx/gfx_structs.v
- [x] sokol/sapp/enums.v
- [x] sokol/sapp/sapp_structs.v
- [x] sqlite/orm.v
- [x] sync/sync_default.c.v
- [x] sync/sync_macos.c.v
- [x] sync/sync_windows.c.v
- [x] szip/szip.v
- [x] v/builder/builder.v
- [x] v/builder/compile.v
- [x] v/doc/doc.v
- [x] v/fmt/comments.v
- [x] v/gen/c/array.v
- [x] v/gen/c/cmain.v
- [x] v/gen/c/comptime.v
- [x] v/gen/c/embed.v
- [x] v/gen/c/index.v
- [x] v/gen/c/live.v
- [x] v/gen/c/sql.v
- [x] v/parser/comptime.v
- [x] v/parser/module.v
- [x] v/parser/tmpl.v
- [x] v/pkgconfig/pkgconfig.v - Problem can be fixed once we update the string interpolation syntax
- [x] v/scanner/scanner.v
- [x] v/transformer/transformer.v
- [x] v/util/util.v
- [x] v/vmod/parser.v
- [x] vweb/assets/assets.v - refer to #16 
- [ ] vweb/vweb.v - Problem can be fixed once we update the string interpolation syntax

Files remaining (as of 18th August 2021):
- [x] gg/gg.c.v  
- [ ] gg/gg.v - Needs the updated `1.0` float syntax over `1.`
- [x] gg/image.c.v  
- [x] gg/image.v  
- [ ] mssql/\_cdefs.c.v  
- [x] mssql/stmt_handle.v  
- [ ] net/aasocket.c.v  
- [ ] net/address.v  
- [ ] net/common.v  
- [ ] net/http/download_windows.c.v  
- [ ] net/http/header.v  
- [ ] net/http/http.v  
- [ ] net/http/server.v  
- [ ] net/openssl/ssl_connection.v  
- [ ] net/tcp.v  
- [ ] net/udp.v  
- [ ] net/unix/common.v  
- [ ] net/websocket/websocket_client.v  
- [ ] orm/orm.v
- [ ] pg/orm.v - refer to #17 
- [x] picoev/picoev.v
- [x] rand/rand.v  
- [x] rand/util/util.v  
- [ ] readline/readline_linux.c.v  
- [ ] regex/regex.v  
- [ ] sokol/gfx/enums.v  
- [x] strconv/atof.v  
- [ ] strconv/vprintf.v  
- [ ] sync/channels.v  
- [ ] sync/pool/pool.v  
- [ ] term/term_windows.c.v  
- [ ] term/ui/consoleapi_windows.c.v  
- [ ] term/ui/input_nix.c.v  
- [ ] term/ui/input_windows.c.v  
- [ ] term/ui/termios_nix.c.v  
- [ ] term/ui/ui.v  
- [x] time/parse.c.v  
- [ ] time/time_nix.c.v  
- [ ] v/ast/ast.v  
- [ ] v/ast/scope.v  
- [ ] v/ast/str.v  
- [ ] v/ast/table.v  
- [ ] v/ast/types.v  
- [ ] v/callgraph/callgraph.v  
- [ ] v/checker/check_types.v  
- [ ] v/checker/checker.v  
- [ ] v/fmt/fmt.v  
- [ ] v/gen/c/assert.v  
- [ ] v/gen/c/auto_str_methods.v  
- [ ] v/gen/c/cgen.v  
- [ ] v/gen/c/fn.v  
- [ ] v/gen/c/infix_expr.v  
- [ ] v/gen/c/str.v  
- [ ] v/gen/native/amd64.v  
- [ ] v/gen/native/elf_obj.v  
- [ ] v/live/common.v  
- [ ] v/markused/walker.v  
- [ ] v/parser/expr.v  
- [ ] v/parser/fn.v  
- [ ] v/parser/parser.v  
- [ ] v/parser/struct.v  
- [ ] v/token/token.v  
- [x] v/util/errors.v  
- [x] v/util/util.v  
- [ ] vweb/vweb.v

**Comment by nedpals** [comment]
NOTE:
rand/util/util.v:10 `array` is used as an identifier

**Comment by nedpals** [comment]
`vlib/vweb/assets/assets.v` is affected by issue #9

**Comment by nedpals** [comment]
`vlib/net/http/backend_nix.c.v` is affected similar to issue #9 but for casting expression

**Comment by hungrybluedev** [comment]
The list has been updated to reflect the current count and includes all the missing files.
